FIND_PATH(LIBUSB_INCLUDE_DIR usb.h /usr/local/include /opt/local/include)

FIND_LIBRARY(LIBUSB_LIBRARIES NAMES usb /usr/local/lib /opt/local/lib)

if (LIBUSB_LIBRARIES AND LIBUSB_INCLUDE_DIR)
	SET(LIBUSB_FOUND "YES")
ELSE (LIBUSB_LIBRARIES AND LIBUSB_INCLUDE_DIR)
	SET(LIBUSB_FOUND "NO")
ENDIF (LIBUSB_LIBRARIES AND LIBUSB_INCLUDE_DIR)

IF (LIBUSB_FOUND)
	MESSAGE(STATUS "Found libusb: ${LIBUSB_LIBRARIES}")
ELSE (LIBUSB_FOUND)
	MESSAGE(FATAL_ERROR "Could not find libusb")
ENDIF (LIBUSB_FOUND)

