# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'diag.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_diag(object):
    def setupUi(self, diag):
        diag.setObjectName(_fromUtf8("diag"))
        diag.setEnabled(True)
        diag.resize(580, 620)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(diag.sizePolicy().hasHeightForWidth())
        diag.setSizePolicy(sizePolicy)
        diag.setMinimumSize(QtCore.QSize(580, 620))
        diag.setMaximumSize(QtCore.QSize(580, 620))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(47, 212, 29))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 212, 29))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 213, 211))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Link, brush)
        diag.setPalette(palette)
        diag.setAnimated(True)
        diag.setDockNestingEnabled(False)
        self.centralwidget = QtGui.QWidget(diag)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(False)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 581, 581))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_main = QtGui.QWidget()
        self.tab_main.setObjectName(_fromUtf8("tab_main"))
        self.frame = QtGui.QFrame(self.tab_main)
        self.frame.setGeometry(QtCore.QRect(10, 10, 141, 181))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.dial_MainBoth_1 = QtGui.QDial(self.frame)
        self.dial_MainBoth_1.setGeometry(QtCore.QRect(20, 10, 100, 100))
        self.dial_MainBoth_1.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_MainBoth_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dial_MainBoth_1.setMinimum(-7)
        self.dial_MainBoth_1.setMaximum(7)
        self.dial_MainBoth_1.setPageStep(8)
        self.dial_MainBoth_1.setWrapping(False)
        self.dial_MainBoth_1.setNotchesVisible(True)
        self.dial_MainBoth_1.setObjectName(_fromUtf8("dial_MainBoth_1"))
        self.dial_MainLeft_1 = QtGui.QDial(self.frame)
        self.dial_MainLeft_1.setGeometry(QtCore.QRect(10, 120, 61, 50))
        self.dial_MainLeft_1.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_MainLeft_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dial_MainLeft_1.setMinimum(0)
        self.dial_MainLeft_1.setMaximum(7)
        self.dial_MainLeft_1.setPageStep(8)
        self.dial_MainLeft_1.setWrapping(False)
        self.dial_MainLeft_1.setNotchesVisible(True)
        self.dial_MainLeft_1.setObjectName(_fromUtf8("dial_MainLeft_1"))
        self.dial_MainRight_1 = QtGui.QDial(self.frame)
        self.dial_MainRight_1.setGeometry(QtCore.QRect(80, 120, 61, 50))
        self.dial_MainRight_1.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_MainRight_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dial_MainRight_1.setMinimum(0)
        self.dial_MainRight_1.setMaximum(7)
        self.dial_MainRight_1.setPageStep(8)
        self.dial_MainRight_1.setWrapping(False)
        self.dial_MainRight_1.setNotchesVisible(True)
        self.dial_MainRight_1.setObjectName(_fromUtf8("dial_MainRight_1"))
        self.frame_2 = QtGui.QFrame(self.tab_main)
        self.frame_2.setGeometry(QtCore.QRect(150, 10, 141, 181))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.dial_MainBoth_2 = QtGui.QDial(self.frame_2)
        self.dial_MainBoth_2.setGeometry(QtCore.QRect(20, 10, 100, 100))
        self.dial_MainBoth_2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_MainBoth_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dial_MainBoth_2.setMinimum(-7)
        self.dial_MainBoth_2.setMaximum(7)
        self.dial_MainBoth_2.setPageStep(8)
        self.dial_MainBoth_2.setWrapping(False)
        self.dial_MainBoth_2.setNotchesVisible(True)
        self.dial_MainBoth_2.setObjectName(_fromUtf8("dial_MainBoth_2"))
        self.dial_MainLeft_2 = QtGui.QDial(self.frame_2)
        self.dial_MainLeft_2.setGeometry(QtCore.QRect(10, 120, 61, 50))
        self.dial_MainLeft_2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_MainLeft_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dial_MainLeft_2.setMinimum(0)
        self.dial_MainLeft_2.setMaximum(7)
        self.dial_MainLeft_2.setPageStep(8)
        self.dial_MainLeft_2.setWrapping(False)
        self.dial_MainLeft_2.setNotchesVisible(True)
        self.dial_MainLeft_2.setObjectName(_fromUtf8("dial_MainLeft_2"))
        self.dial_MainRight_2 = QtGui.QDial(self.frame_2)
        self.dial_MainRight_2.setGeometry(QtCore.QRect(80, 120, 61, 50))
        self.dial_MainRight_2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_MainRight_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dial_MainRight_2.setMinimum(0)
        self.dial_MainRight_2.setMaximum(7)
        self.dial_MainRight_2.setPageStep(8)
        self.dial_MainRight_2.setWrapping(False)
        self.dial_MainRight_2.setNotchesVisible(True)
        self.dial_MainRight_2.setObjectName(_fromUtf8("dial_MainRight_2"))
        self.frame_3 = QtGui.QFrame(self.tab_main)
        self.frame_3.setGeometry(QtCore.QRect(290, 10, 141, 181))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.dial_MainBoth_3 = QtGui.QDial(self.frame_3)
        self.dial_MainBoth_3.setGeometry(QtCore.QRect(20, 10, 100, 100))
        self.dial_MainBoth_3.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_MainBoth_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dial_MainBoth_3.setMinimum(-7)
        self.dial_MainBoth_3.setMaximum(7)
        self.dial_MainBoth_3.setPageStep(8)
        self.dial_MainBoth_3.setWrapping(False)
        self.dial_MainBoth_3.setNotchesVisible(True)
        self.dial_MainBoth_3.setObjectName(_fromUtf8("dial_MainBoth_3"))
        self.dial_MainLeft_3 = QtGui.QDial(self.frame_3)
        self.dial_MainLeft_3.setGeometry(QtCore.QRect(10, 120, 61, 50))
        self.dial_MainLeft_3.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_MainLeft_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dial_MainLeft_3.setMinimum(0)
        self.dial_MainLeft_3.setMaximum(7)
        self.dial_MainLeft_3.setPageStep(8)
        self.dial_MainLeft_3.setWrapping(False)
        self.dial_MainLeft_3.setNotchesVisible(True)
        self.dial_MainLeft_3.setObjectName(_fromUtf8("dial_MainLeft_3"))
        self.dial_MainRight_3 = QtGui.QDial(self.frame_3)
        self.dial_MainRight_3.setGeometry(QtCore.QRect(80, 120, 61, 50))
        self.dial_MainRight_3.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_MainRight_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dial_MainRight_3.setMinimum(0)
        self.dial_MainRight_3.setMaximum(7)
        self.dial_MainRight_3.setPageStep(8)
        self.dial_MainRight_3.setWrapping(False)
        self.dial_MainRight_3.setNotchesVisible(True)
        self.dial_MainRight_3.setObjectName(_fromUtf8("dial_MainRight_3"))
        self.frame_4 = QtGui.QFrame(self.tab_main)
        self.frame_4.setGeometry(QtCore.QRect(430, 10, 141, 181))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.dial_MainBoth_4 = QtGui.QDial(self.frame_4)
        self.dial_MainBoth_4.setGeometry(QtCore.QRect(20, 10, 100, 100))
        self.dial_MainBoth_4.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_MainBoth_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dial_MainBoth_4.setMinimum(-7)
        self.dial_MainBoth_4.setMaximum(7)
        self.dial_MainBoth_4.setPageStep(8)
        self.dial_MainBoth_4.setWrapping(False)
        self.dial_MainBoth_4.setNotchesVisible(True)
        self.dial_MainBoth_4.setObjectName(_fromUtf8("dial_MainBoth_4"))
        self.dial_MainLeft_4 = QtGui.QDial(self.frame_4)
        self.dial_MainLeft_4.setGeometry(QtCore.QRect(10, 120, 61, 50))
        self.dial_MainLeft_4.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_MainLeft_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dial_MainLeft_4.setMinimum(0)
        self.dial_MainLeft_4.setMaximum(7)
        self.dial_MainLeft_4.setPageStep(8)
        self.dial_MainLeft_4.setWrapping(False)
        self.dial_MainLeft_4.setNotchesVisible(True)
        self.dial_MainLeft_4.setObjectName(_fromUtf8("dial_MainLeft_4"))
        self.dial_MainRight_4 = QtGui.QDial(self.frame_4)
        self.dial_MainRight_4.setGeometry(QtCore.QRect(80, 120, 61, 50))
        self.dial_MainRight_4.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_MainRight_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dial_MainRight_4.setMinimum(0)
        self.dial_MainRight_4.setMaximum(7)
        self.dial_MainRight_4.setPageStep(8)
        self.dial_MainRight_4.setWrapping(False)
        self.dial_MainRight_4.setNotchesVisible(True)
        self.dial_MainRight_4.setObjectName(_fromUtf8("dial_MainRight_4"))
        self.verticalLayout = QtGui.QWidget(self.tab_main)
        self.verticalLayout.setGeometry(QtCore.QRect(10, 210, 160, 284))
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.vboxlayout = QtGui.QVBoxLayout(self.verticalLayout)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.radioButton_MainDigital_1 = QtGui.QRadioButton(self.verticalLayout)
        self.radioButton_MainDigital_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_MainDigital_1.setCheckable(False)
        self.radioButton_MainDigital_1.setChecked(False)
        self.radioButton_MainDigital_1.setAutoExclusive(False)
        self.radioButton_MainDigital_1.setObjectName(_fromUtf8("radioButton_MainDigital_1"))
        self.vboxlayout.addWidget(self.radioButton_MainDigital_1)
        self.radioButton_MainDigital_2 = QtGui.QRadioButton(self.verticalLayout)
        self.radioButton_MainDigital_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_MainDigital_2.setCheckable(False)
        self.radioButton_MainDigital_2.setAutoExclusive(False)
        self.radioButton_MainDigital_2.setObjectName(_fromUtf8("radioButton_MainDigital_2"))
        self.vboxlayout.addWidget(self.radioButton_MainDigital_2)
        self.radioButton_MainDigital_3 = QtGui.QRadioButton(self.verticalLayout)
        self.radioButton_MainDigital_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_MainDigital_3.setCheckable(False)
        self.radioButton_MainDigital_3.setAutoExclusive(False)
        self.radioButton_MainDigital_3.setObjectName(_fromUtf8("radioButton_MainDigital_3"))
        self.vboxlayout.addWidget(self.radioButton_MainDigital_3)
        self.radioButton_MainDigital_4 = QtGui.QRadioButton(self.verticalLayout)
        self.radioButton_MainDigital_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_MainDigital_4.setCheckable(False)
        self.radioButton_MainDigital_4.setAutoExclusive(False)
        self.radioButton_MainDigital_4.setObjectName(_fromUtf8("radioButton_MainDigital_4"))
        self.vboxlayout.addWidget(self.radioButton_MainDigital_4)
        self.radioButton_MainDigital_5 = QtGui.QRadioButton(self.verticalLayout)
        self.radioButton_MainDigital_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_MainDigital_5.setCheckable(False)
        self.radioButton_MainDigital_5.setAutoExclusive(False)
        self.radioButton_MainDigital_5.setObjectName(_fromUtf8("radioButton_MainDigital_5"))
        self.vboxlayout.addWidget(self.radioButton_MainDigital_5)
        self.radioButton_MainDigital_6 = QtGui.QRadioButton(self.verticalLayout)
        self.radioButton_MainDigital_6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_MainDigital_6.setCheckable(False)
        self.radioButton_MainDigital_6.setAutoExclusive(False)
        self.radioButton_MainDigital_6.setObjectName(_fromUtf8("radioButton_MainDigital_6"))
        self.vboxlayout.addWidget(self.radioButton_MainDigital_6)
        self.radioButton_MainDigital_7 = QtGui.QRadioButton(self.verticalLayout)
        self.radioButton_MainDigital_7.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_MainDigital_7.setCheckable(False)
        self.radioButton_MainDigital_7.setAutoExclusive(False)
        self.radioButton_MainDigital_7.setObjectName(_fromUtf8("radioButton_MainDigital_7"))
        self.vboxlayout.addWidget(self.radioButton_MainDigital_7)
        self.radioButton_MainDigital_8 = QtGui.QRadioButton(self.verticalLayout)
        self.radioButton_MainDigital_8.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_MainDigital_8.setCheckable(False)
        self.radioButton_MainDigital_8.setAutoExclusive(False)
        self.radioButton_MainDigital_8.setObjectName(_fromUtf8("radioButton_MainDigital_8"))
        self.vboxlayout.addWidget(self.radioButton_MainDigital_8)
        self.progressBar_Voltage = QtGui.QProgressBar(self.tab_main)
        self.progressBar_Voltage.setGeometry(QtCore.QRect(400, 280, 161, 23))
        self.progressBar_Voltage.setMaximum(12)
        self.progressBar_Voltage.setProperty("value", 0)
        self.progressBar_Voltage.setObjectName(_fromUtf8("progressBar_Voltage"))
        self.lcdNumber_AX = QtGui.QLCDNumber(self.tab_main)
        self.lcdNumber_AX.setGeometry(QtCore.QRect(200, 210, 64, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(20, 19, 18))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 19, 18))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.lcdNumber_AX.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lcdNumber_AX.setFont(font)
        self.lcdNumber_AX.setNumDigits(4)
        self.lcdNumber_AX.setProperty("value", 0.0)
        self.lcdNumber_AX.setProperty("intValue", 0)
        self.lcdNumber_AX.setObjectName(_fromUtf8("lcdNumber_AX"))
        self.lcdNumber_AY = QtGui.QLCDNumber(self.tab_main)
        self.lcdNumber_AY.setGeometry(QtCore.QRect(300, 210, 64, 23))
        self.lcdNumber_AY.setNumDigits(4)
        self.lcdNumber_AY.setProperty("value", 0.0)
        self.lcdNumber_AY.setProperty("intValue", 0)
        self.lcdNumber_AY.setObjectName(_fromUtf8("lcdNumber_AY"))
        self.lcdNumber_A1 = QtGui.QLCDNumber(self.tab_main)
        self.lcdNumber_A1.setGeometry(QtCore.QRect(200, 280, 64, 23))
        self.lcdNumber_A1.setNumDigits(4)
        self.lcdNumber_A1.setProperty("value", 0.0)
        self.lcdNumber_A1.setProperty("intValue", 0)
        self.lcdNumber_A1.setObjectName(_fromUtf8("lcdNumber_A1"))
        self.lcdNumber_A2 = QtGui.QLCDNumber(self.tab_main)
        self.lcdNumber_A2.setGeometry(QtCore.QRect(300, 280, 64, 23))
        self.lcdNumber_A2.setNumDigits(4)
        self.lcdNumber_A2.setProperty("value", 0.0)
        self.lcdNumber_A2.setProperty("intValue", 0)
        self.lcdNumber_A2.setObjectName(_fromUtf8("lcdNumber_A2"))
        self.lcdNumber_AZ = QtGui.QLCDNumber(self.tab_main)
        self.lcdNumber_AZ.setGeometry(QtCore.QRect(400, 210, 64, 23))
        self.lcdNumber_AZ.setNumDigits(4)
        self.lcdNumber_AZ.setProperty("value", 0.0)
        self.lcdNumber_AZ.setProperty("intValue", 0)
        self.lcdNumber_AZ.setObjectName(_fromUtf8("lcdNumber_AZ"))
        self.lcdNumber_IR = QtGui.QLCDNumber(self.tab_main)
        self.lcdNumber_IR.setGeometry(QtCore.QRect(210, 460, 91, 41))
        self.lcdNumber_IR.setNumDigits(4)
        self.lcdNumber_IR.setProperty("value", 0.0)
        self.lcdNumber_IR.setProperty("intValue", 0)
        self.lcdNumber_IR.setObjectName(_fromUtf8("lcdNumber_IR"))
        self.label = QtGui.QLabel(self.tab_main)
        self.label.setGeometry(QtCore.QRect(210, 500, 60, 18))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.tab_main)
        self.label_2.setGeometry(QtCore.QRect(200, 240, 60, 18))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.tab_main)
        self.label_3.setGeometry(QtCore.QRect(300, 240, 60, 18))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.tab_main)
        self.label_4.setGeometry(QtCore.QRect(400, 240, 60, 18))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.tab_main)
        self.label_5.setGeometry(QtCore.QRect(200, 310, 60, 18))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.tab_main)
        self.label_6.setGeometry(QtCore.QRect(300, 310, 60, 18))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.tab_main)
        self.label_7.setGeometry(QtCore.QRect(400, 310, 60, 18))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.tab_main)
        self.label_8.setGeometry(QtCore.QRect(60, 190, 60, 18))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.tab_main)
        self.label_9.setGeometry(QtCore.QRect(190, 190, 71, 18))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.tab_main)
        self.label_10.setGeometry(QtCore.QRect(330, 190, 71, 18))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.tab_main)
        self.label_11.setGeometry(QtCore.QRect(470, 190, 71, 18))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.pushButton_Stop = QtGui.QPushButton(self.tab_main)
        self.pushButton_Stop.setGeometry(QtCore.QRect(420, 410, 83, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(151, 150, 149))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.pushButton_Stop.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Stop.setFont(font)
        self.pushButton_Stop.setObjectName(_fromUtf8("pushButton_Stop"))
        self.lcdNumber_D1 = QtGui.QLCDNumber(self.tab_main)
        self.lcdNumber_D1.setGeometry(QtCore.QRect(200, 350, 64, 23))
        self.lcdNumber_D1.setNumDigits(4)
        self.lcdNumber_D1.setProperty("value", 0.0)
        self.lcdNumber_D1.setProperty("intValue", 0)
        self.lcdNumber_D1.setObjectName(_fromUtf8("lcdNumber_D1"))
        self.lcdNumber_D2 = QtGui.QLCDNumber(self.tab_main)
        self.lcdNumber_D2.setGeometry(QtCore.QRect(300, 350, 64, 23))
        self.lcdNumber_D2.setNumDigits(4)
        self.lcdNumber_D2.setProperty("value", 0.0)
        self.lcdNumber_D2.setProperty("intValue", 0)
        self.lcdNumber_D2.setObjectName(_fromUtf8("lcdNumber_D2"))
        self.label_27 = QtGui.QLabel(self.tab_main)
        self.label_27.setGeometry(QtCore.QRect(200, 380, 60, 18))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_28 = QtGui.QLabel(self.tab_main)
        self.label_28.setGeometry(QtCore.QRect(300, 380, 60, 18))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.checkBoxConnection_Main = QtGui.QCheckBox(self.tab_main)
        self.checkBoxConnection_Main.setGeometry(QtCore.QRect(400, 350, 121, 23))
        self.checkBoxConnection_Main.setObjectName(_fromUtf8("checkBoxConnection_Main"))
        self.tabWidget.addTab(self.tab_main, _fromUtf8(""))
        self.tab_slave1 = QtGui.QWidget()
        self.tab_slave1.setObjectName(_fromUtf8("tab_slave1"))
        self.frame_5 = QtGui.QFrame(self.tab_slave1)
        self.frame_5.setGeometry(QtCore.QRect(10, 10, 141, 181))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.dial_Slave1Both_1 = QtGui.QDial(self.frame_5)
        self.dial_Slave1Both_1.setGeometry(QtCore.QRect(20, 10, 100, 100))
        self.dial_Slave1Both_1.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_Slave1Both_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dial_Slave1Both_1.setMinimum(-7)
        self.dial_Slave1Both_1.setMaximum(7)
        self.dial_Slave1Both_1.setPageStep(8)
        self.dial_Slave1Both_1.setWrapping(False)
        self.dial_Slave1Both_1.setNotchesVisible(True)
        self.dial_Slave1Both_1.setObjectName(_fromUtf8("dial_Slave1Both_1"))
        self.dial_Slave1Left_1 = QtGui.QDial(self.frame_5)
        self.dial_Slave1Left_1.setGeometry(QtCore.QRect(10, 120, 61, 50))
        self.dial_Slave1Left_1.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_Slave1Left_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dial_Slave1Left_1.setMinimum(0)
        self.dial_Slave1Left_1.setMaximum(7)
        self.dial_Slave1Left_1.setPageStep(8)
        self.dial_Slave1Left_1.setWrapping(False)
        self.dial_Slave1Left_1.setNotchesVisible(True)
        self.dial_Slave1Left_1.setObjectName(_fromUtf8("dial_Slave1Left_1"))
        self.dial_Slave1Right_1 = QtGui.QDial(self.frame_5)
        self.dial_Slave1Right_1.setGeometry(QtCore.QRect(80, 120, 61, 50))
        self.dial_Slave1Right_1.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_Slave1Right_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dial_Slave1Right_1.setMinimum(0)
        self.dial_Slave1Right_1.setMaximum(7)
        self.dial_Slave1Right_1.setPageStep(8)
        self.dial_Slave1Right_1.setWrapping(False)
        self.dial_Slave1Right_1.setNotchesVisible(True)
        self.dial_Slave1Right_1.setObjectName(_fromUtf8("dial_Slave1Right_1"))
        self.frame_6 = QtGui.QFrame(self.tab_slave1)
        self.frame_6.setGeometry(QtCore.QRect(150, 10, 141, 181))
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.dial_Slave1Both_2 = QtGui.QDial(self.frame_6)
        self.dial_Slave1Both_2.setGeometry(QtCore.QRect(20, 10, 100, 100))
        self.dial_Slave1Both_2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_Slave1Both_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dial_Slave1Both_2.setMinimum(-7)
        self.dial_Slave1Both_2.setMaximum(7)
        self.dial_Slave1Both_2.setPageStep(8)
        self.dial_Slave1Both_2.setWrapping(False)
        self.dial_Slave1Both_2.setNotchesVisible(True)
        self.dial_Slave1Both_2.setObjectName(_fromUtf8("dial_Slave1Both_2"))
        self.dial_Slave1Left_2 = QtGui.QDial(self.frame_6)
        self.dial_Slave1Left_2.setGeometry(QtCore.QRect(10, 120, 61, 50))
        self.dial_Slave1Left_2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_Slave1Left_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dial_Slave1Left_2.setMinimum(0)
        self.dial_Slave1Left_2.setMaximum(7)
        self.dial_Slave1Left_2.setPageStep(8)
        self.dial_Slave1Left_2.setWrapping(False)
        self.dial_Slave1Left_2.setNotchesVisible(True)
        self.dial_Slave1Left_2.setObjectName(_fromUtf8("dial_Slave1Left_2"))
        self.dial_Slave1Right_2 = QtGui.QDial(self.frame_6)
        self.dial_Slave1Right_2.setGeometry(QtCore.QRect(80, 120, 61, 50))
        self.dial_Slave1Right_2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_Slave1Right_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dial_Slave1Right_2.setMinimum(0)
        self.dial_Slave1Right_2.setMaximum(7)
        self.dial_Slave1Right_2.setPageStep(8)
        self.dial_Slave1Right_2.setWrapping(False)
        self.dial_Slave1Right_2.setNotchesVisible(True)
        self.dial_Slave1Right_2.setObjectName(_fromUtf8("dial_Slave1Right_2"))
        self.frame_7 = QtGui.QFrame(self.tab_slave1)
        self.frame_7.setGeometry(QtCore.QRect(290, 10, 141, 181))
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.dial_Slave1Both_3 = QtGui.QDial(self.frame_7)
        self.dial_Slave1Both_3.setGeometry(QtCore.QRect(20, 10, 100, 100))
        self.dial_Slave1Both_3.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_Slave1Both_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dial_Slave1Both_3.setMinimum(-7)
        self.dial_Slave1Both_3.setMaximum(7)
        self.dial_Slave1Both_3.setPageStep(8)
        self.dial_Slave1Both_3.setWrapping(False)
        self.dial_Slave1Both_3.setNotchesVisible(True)
        self.dial_Slave1Both_3.setObjectName(_fromUtf8("dial_Slave1Both_3"))
        self.dial_Slave1Left_3 = QtGui.QDial(self.frame_7)
        self.dial_Slave1Left_3.setGeometry(QtCore.QRect(10, 120, 61, 50))
        self.dial_Slave1Left_3.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_Slave1Left_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dial_Slave1Left_3.setMinimum(0)
        self.dial_Slave1Left_3.setMaximum(7)
        self.dial_Slave1Left_3.setPageStep(8)
        self.dial_Slave1Left_3.setWrapping(False)
        self.dial_Slave1Left_3.setNotchesVisible(True)
        self.dial_Slave1Left_3.setObjectName(_fromUtf8("dial_Slave1Left_3"))
        self.dial_Slave1Right_3 = QtGui.QDial(self.frame_7)
        self.dial_Slave1Right_3.setGeometry(QtCore.QRect(80, 120, 61, 50))
        self.dial_Slave1Right_3.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_Slave1Right_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dial_Slave1Right_3.setMinimum(0)
        self.dial_Slave1Right_3.setMaximum(7)
        self.dial_Slave1Right_3.setPageStep(8)
        self.dial_Slave1Right_3.setWrapping(False)
        self.dial_Slave1Right_3.setNotchesVisible(True)
        self.dial_Slave1Right_3.setObjectName(_fromUtf8("dial_Slave1Right_3"))
        self.frame_8 = QtGui.QFrame(self.tab_slave1)
        self.frame_8.setGeometry(QtCore.QRect(430, 10, 141, 181))
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.dial_Slave1Both_4 = QtGui.QDial(self.frame_8)
        self.dial_Slave1Both_4.setGeometry(QtCore.QRect(20, 10, 100, 100))
        self.dial_Slave1Both_4.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_Slave1Both_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dial_Slave1Both_4.setMinimum(-7)
        self.dial_Slave1Both_4.setMaximum(7)
        self.dial_Slave1Both_4.setPageStep(8)
        self.dial_Slave1Both_4.setWrapping(False)
        self.dial_Slave1Both_4.setNotchesVisible(True)
        self.dial_Slave1Both_4.setObjectName(_fromUtf8("dial_Slave1Both_4"))
        self.dial_Slave1Left_4 = QtGui.QDial(self.frame_8)
        self.dial_Slave1Left_4.setGeometry(QtCore.QRect(10, 120, 61, 50))
        self.dial_Slave1Left_4.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_Slave1Left_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dial_Slave1Left_4.setMinimum(0)
        self.dial_Slave1Left_4.setMaximum(7)
        self.dial_Slave1Left_4.setPageStep(8)
        self.dial_Slave1Left_4.setWrapping(False)
        self.dial_Slave1Left_4.setNotchesVisible(True)
        self.dial_Slave1Left_4.setObjectName(_fromUtf8("dial_Slave1Left_4"))
        self.dial_Slave1Right_4 = QtGui.QDial(self.frame_8)
        self.dial_Slave1Right_4.setGeometry(QtCore.QRect(80, 120, 61, 50))
        self.dial_Slave1Right_4.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_Slave1Right_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dial_Slave1Right_4.setMinimum(0)
        self.dial_Slave1Right_4.setMaximum(7)
        self.dial_Slave1Right_4.setPageStep(8)
        self.dial_Slave1Right_4.setWrapping(False)
        self.dial_Slave1Right_4.setNotchesVisible(True)
        self.dial_Slave1Right_4.setObjectName(_fromUtf8("dial_Slave1Right_4"))
        self.verticalLayout_2 = QtGui.QWidget(self.tab_slave1)
        self.verticalLayout_2.setGeometry(QtCore.QRect(10, 210, 160, 284))
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self._3 = QtGui.QVBoxLayout(self.verticalLayout_2)
        self._3.setObjectName(_fromUtf8("_3"))
        self.radioButton_Slave1Digital_1 = QtGui.QRadioButton(self.verticalLayout_2)
        self.radioButton_Slave1Digital_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_Slave1Digital_1.setCheckable(False)
        self.radioButton_Slave1Digital_1.setChecked(False)
        self.radioButton_Slave1Digital_1.setAutoExclusive(False)
        self.radioButton_Slave1Digital_1.setObjectName(_fromUtf8("radioButton_Slave1Digital_1"))
        self._3.addWidget(self.radioButton_Slave1Digital_1)
        self.radioButton_Slave1Digital_2 = QtGui.QRadioButton(self.verticalLayout_2)
        self.radioButton_Slave1Digital_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_Slave1Digital_2.setCheckable(False)
        self.radioButton_Slave1Digital_2.setAutoExclusive(False)
        self.radioButton_Slave1Digital_2.setObjectName(_fromUtf8("radioButton_Slave1Digital_2"))
        self._3.addWidget(self.radioButton_Slave1Digital_2)
        self.radioButton_Slave1Digital_3 = QtGui.QRadioButton(self.verticalLayout_2)
        self.radioButton_Slave1Digital_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_Slave1Digital_3.setCheckable(False)
        self.radioButton_Slave1Digital_3.setAutoExclusive(False)
        self.radioButton_Slave1Digital_3.setObjectName(_fromUtf8("radioButton_Slave1Digital_3"))
        self._3.addWidget(self.radioButton_Slave1Digital_3)
        self.radioButton_Slave1Digital_4 = QtGui.QRadioButton(self.verticalLayout_2)
        self.radioButton_Slave1Digital_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_Slave1Digital_4.setCheckable(False)
        self.radioButton_Slave1Digital_4.setAutoExclusive(False)
        self.radioButton_Slave1Digital_4.setObjectName(_fromUtf8("radioButton_Slave1Digital_4"))
        self._3.addWidget(self.radioButton_Slave1Digital_4)
        self.radioButton_Slave1Digital_5 = QtGui.QRadioButton(self.verticalLayout_2)
        self.radioButton_Slave1Digital_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_Slave1Digital_5.setCheckable(False)
        self.radioButton_Slave1Digital_5.setAutoExclusive(False)
        self.radioButton_Slave1Digital_5.setObjectName(_fromUtf8("radioButton_Slave1Digital_5"))
        self._3.addWidget(self.radioButton_Slave1Digital_5)
        self.radioButton_Slave1Digital_6 = QtGui.QRadioButton(self.verticalLayout_2)
        self.radioButton_Slave1Digital_6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_Slave1Digital_6.setCheckable(False)
        self.radioButton_Slave1Digital_6.setAutoExclusive(False)
        self.radioButton_Slave1Digital_6.setObjectName(_fromUtf8("radioButton_Slave1Digital_6"))
        self._3.addWidget(self.radioButton_Slave1Digital_6)
        self.radioButton_Slave1Digital_7 = QtGui.QRadioButton(self.verticalLayout_2)
        self.radioButton_Slave1Digital_7.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_Slave1Digital_7.setCheckable(False)
        self.radioButton_Slave1Digital_7.setAutoExclusive(False)
        self.radioButton_Slave1Digital_7.setObjectName(_fromUtf8("radioButton_Slave1Digital_7"))
        self._3.addWidget(self.radioButton_Slave1Digital_7)
        self.radioButton_Slave1Digital_8 = QtGui.QRadioButton(self.verticalLayout_2)
        self.radioButton_Slave1Digital_8.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_Slave1Digital_8.setCheckable(False)
        self.radioButton_Slave1Digital_8.setAutoExclusive(False)
        self.radioButton_Slave1Digital_8.setObjectName(_fromUtf8("radioButton_Slave1Digital_8"))
        self._3.addWidget(self.radioButton_Slave1Digital_8)
        self.radioButton_Slave1Digital_1.raise_()
        self.radioButton_Slave1Digital_2.raise_()
        self.radioButton_Slave1Digital_4.raise_()
        self.radioButton_Slave1Digital_5.raise_()
        self.radioButton_Slave1Digital_6.raise_()
        self.radioButton_Slave1Digital_7.raise_()
        self.radioButton_Slave1Digital_8.raise_()
        self.radioButton_Slave1Digital_3.raise_()
        self.lcdNumber_AX_Slave1 = QtGui.QLCDNumber(self.tab_slave1)
        self.lcdNumber_AX_Slave1.setGeometry(QtCore.QRect(200, 210, 64, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(20, 19, 18))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 19, 18))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.lcdNumber_AX_Slave1.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lcdNumber_AX_Slave1.setFont(font)
        self.lcdNumber_AX_Slave1.setNumDigits(4)
        self.lcdNumber_AX_Slave1.setProperty("value", 0.0)
        self.lcdNumber_AX_Slave1.setProperty("intValue", 0)
        self.lcdNumber_AX_Slave1.setObjectName(_fromUtf8("lcdNumber_AX_Slave1"))
        self.label_12 = QtGui.QLabel(self.tab_slave1)
        self.label_12.setGeometry(QtCore.QRect(200, 240, 60, 18))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.pushButton_Stop_2 = QtGui.QPushButton(self.tab_slave1)
        self.pushButton_Stop_2.setGeometry(QtCore.QRect(420, 410, 83, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(151, 150, 149))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.pushButton_Stop_2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Stop_2.setFont(font)
        self.pushButton_Stop_2.setObjectName(_fromUtf8("pushButton_Stop_2"))
        self.label_13 = QtGui.QLabel(self.tab_slave1)
        self.label_13.setGeometry(QtCore.QRect(60, 190, 60, 18))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.tab_slave1)
        self.label_14.setGeometry(QtCore.QRect(190, 190, 71, 18))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.tab_slave1)
        self.label_15.setGeometry(QtCore.QRect(330, 190, 71, 18))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.tab_slave1)
        self.label_16.setGeometry(QtCore.QRect(470, 190, 71, 18))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.progressBar_Voltage_Slave1 = QtGui.QProgressBar(self.tab_slave1)
        self.progressBar_Voltage_Slave1.setGeometry(QtCore.QRect(300, 210, 161, 23))
        self.progressBar_Voltage_Slave1.setMaximum(12)
        self.progressBar_Voltage_Slave1.setProperty("value", 0)
        self.progressBar_Voltage_Slave1.setObjectName(_fromUtf8("progressBar_Voltage_Slave1"))
        self.label_29 = QtGui.QLabel(self.tab_slave1)
        self.label_29.setGeometry(QtCore.QRect(300, 240, 60, 18))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.checkBoxConnection_Slave1 = QtGui.QCheckBox(self.tab_slave1)
        self.checkBoxConnection_Slave1.setGeometry(QtCore.QRect(400, 350, 121, 23))
        self.checkBoxConnection_Slave1.setObjectName(_fromUtf8("checkBoxConnection_Slave1"))
        self.tabWidget.addTab(self.tab_slave1, _fromUtf8(""))
        self.tab_slave2 = QtGui.QWidget()
        self.tab_slave2.setObjectName(_fromUtf8("tab_slave2"))
        self.pushButton_Stop_3 = QtGui.QPushButton(self.tab_slave2)
        self.pushButton_Stop_3.setGeometry(QtCore.QRect(420, 410, 83, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(151, 150, 149))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.pushButton_Stop_3.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Stop_3.setFont(font)
        self.pushButton_Stop_3.setObjectName(_fromUtf8("pushButton_Stop_3"))
        self.frame_9 = QtGui.QFrame(self.tab_slave2)
        self.frame_9.setGeometry(QtCore.QRect(10, 10, 141, 181))
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.dial_Slave2Both_1 = QtGui.QDial(self.frame_9)
        self.dial_Slave2Both_1.setGeometry(QtCore.QRect(20, 10, 100, 100))
        self.dial_Slave2Both_1.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_Slave2Both_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dial_Slave2Both_1.setMinimum(-7)
        self.dial_Slave2Both_1.setMaximum(7)
        self.dial_Slave2Both_1.setPageStep(8)
        self.dial_Slave2Both_1.setWrapping(False)
        self.dial_Slave2Both_1.setNotchesVisible(True)
        self.dial_Slave2Both_1.setObjectName(_fromUtf8("dial_Slave2Both_1"))
        self.dial_Slave2Left_1 = QtGui.QDial(self.frame_9)
        self.dial_Slave2Left_1.setGeometry(QtCore.QRect(10, 120, 61, 50))
        self.dial_Slave2Left_1.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_Slave2Left_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dial_Slave2Left_1.setMinimum(0)
        self.dial_Slave2Left_1.setMaximum(7)
        self.dial_Slave2Left_1.setPageStep(8)
        self.dial_Slave2Left_1.setWrapping(False)
        self.dial_Slave2Left_1.setNotchesVisible(True)
        self.dial_Slave2Left_1.setObjectName(_fromUtf8("dial_Slave2Left_1"))
        self.dial_Slave2Right_1 = QtGui.QDial(self.frame_9)
        self.dial_Slave2Right_1.setGeometry(QtCore.QRect(80, 120, 61, 50))
        self.dial_Slave2Right_1.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_Slave2Right_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dial_Slave2Right_1.setMinimum(0)
        self.dial_Slave2Right_1.setMaximum(7)
        self.dial_Slave2Right_1.setPageStep(8)
        self.dial_Slave2Right_1.setWrapping(False)
        self.dial_Slave2Right_1.setNotchesVisible(True)
        self.dial_Slave2Right_1.setObjectName(_fromUtf8("dial_Slave2Right_1"))
        self.frame_10 = QtGui.QFrame(self.tab_slave2)
        self.frame_10.setGeometry(QtCore.QRect(150, 10, 141, 181))
        self.frame_10.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_10.setObjectName(_fromUtf8("frame_10"))
        self.dial_Slave2Both_2 = QtGui.QDial(self.frame_10)
        self.dial_Slave2Both_2.setGeometry(QtCore.QRect(20, 10, 100, 100))
        self.dial_Slave2Both_2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_Slave2Both_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dial_Slave2Both_2.setMinimum(-7)
        self.dial_Slave2Both_2.setMaximum(7)
        self.dial_Slave2Both_2.setPageStep(8)
        self.dial_Slave2Both_2.setWrapping(False)
        self.dial_Slave2Both_2.setNotchesVisible(True)
        self.dial_Slave2Both_2.setObjectName(_fromUtf8("dial_Slave2Both_2"))
        self.dial_Slave2Left_2 = QtGui.QDial(self.frame_10)
        self.dial_Slave2Left_2.setGeometry(QtCore.QRect(10, 120, 61, 50))
        self.dial_Slave2Left_2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_Slave2Left_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dial_Slave2Left_2.setMinimum(0)
        self.dial_Slave2Left_2.setMaximum(7)
        self.dial_Slave2Left_2.setPageStep(8)
        self.dial_Slave2Left_2.setWrapping(False)
        self.dial_Slave2Left_2.setNotchesVisible(True)
        self.dial_Slave2Left_2.setObjectName(_fromUtf8("dial_Slave2Left_2"))
        self.dial_Slave2Right_2 = QtGui.QDial(self.frame_10)
        self.dial_Slave2Right_2.setGeometry(QtCore.QRect(80, 120, 61, 50))
        self.dial_Slave2Right_2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_Slave2Right_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dial_Slave2Right_2.setMinimum(0)
        self.dial_Slave2Right_2.setMaximum(7)
        self.dial_Slave2Right_2.setPageStep(8)
        self.dial_Slave2Right_2.setWrapping(False)
        self.dial_Slave2Right_2.setNotchesVisible(True)
        self.dial_Slave2Right_2.setObjectName(_fromUtf8("dial_Slave2Right_2"))
        self.frame_11 = QtGui.QFrame(self.tab_slave2)
        self.frame_11.setGeometry(QtCore.QRect(290, 10, 141, 181))
        self.frame_11.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_11.setObjectName(_fromUtf8("frame_11"))
        self.dial_Slave2Both_3 = QtGui.QDial(self.frame_11)
        self.dial_Slave2Both_3.setGeometry(QtCore.QRect(20, 10, 100, 100))
        self.dial_Slave2Both_3.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_Slave2Both_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dial_Slave2Both_3.setMinimum(-7)
        self.dial_Slave2Both_3.setMaximum(7)
        self.dial_Slave2Both_3.setPageStep(8)
        self.dial_Slave2Both_3.setWrapping(False)
        self.dial_Slave2Both_3.setNotchesVisible(True)
        self.dial_Slave2Both_3.setObjectName(_fromUtf8("dial_Slave2Both_3"))
        self.dial_Slave2Left_3 = QtGui.QDial(self.frame_11)
        self.dial_Slave2Left_3.setGeometry(QtCore.QRect(10, 120, 61, 50))
        self.dial_Slave2Left_3.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_Slave2Left_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dial_Slave2Left_3.setMinimum(0)
        self.dial_Slave2Left_3.setMaximum(7)
        self.dial_Slave2Left_3.setPageStep(8)
        self.dial_Slave2Left_3.setWrapping(False)
        self.dial_Slave2Left_3.setNotchesVisible(True)
        self.dial_Slave2Left_3.setObjectName(_fromUtf8("dial_Slave2Left_3"))
        self.dial_Slave2Right_3 = QtGui.QDial(self.frame_11)
        self.dial_Slave2Right_3.setGeometry(QtCore.QRect(80, 120, 61, 50))
        self.dial_Slave2Right_3.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_Slave2Right_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dial_Slave2Right_3.setMinimum(0)
        self.dial_Slave2Right_3.setMaximum(7)
        self.dial_Slave2Right_3.setPageStep(8)
        self.dial_Slave2Right_3.setWrapping(False)
        self.dial_Slave2Right_3.setNotchesVisible(True)
        self.dial_Slave2Right_3.setObjectName(_fromUtf8("dial_Slave2Right_3"))
        self.frame_12 = QtGui.QFrame(self.tab_slave2)
        self.frame_12.setGeometry(QtCore.QRect(430, 10, 141, 181))
        self.frame_12.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_12.setObjectName(_fromUtf8("frame_12"))
        self.dial_Slave2Both_4 = QtGui.QDial(self.frame_12)
        self.dial_Slave2Both_4.setGeometry(QtCore.QRect(20, 10, 100, 100))
        self.dial_Slave2Both_4.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_Slave2Both_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dial_Slave2Both_4.setMinimum(-7)
        self.dial_Slave2Both_4.setMaximum(7)
        self.dial_Slave2Both_4.setPageStep(8)
        self.dial_Slave2Both_4.setWrapping(False)
        self.dial_Slave2Both_4.setNotchesVisible(True)
        self.dial_Slave2Both_4.setObjectName(_fromUtf8("dial_Slave2Both_4"))
        self.dial_Slave2Left_4 = QtGui.QDial(self.frame_12)
        self.dial_Slave2Left_4.setGeometry(QtCore.QRect(10, 120, 61, 50))
        self.dial_Slave2Left_4.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_Slave2Left_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dial_Slave2Left_4.setMinimum(0)
        self.dial_Slave2Left_4.setMaximum(7)
        self.dial_Slave2Left_4.setPageStep(8)
        self.dial_Slave2Left_4.setWrapping(False)
        self.dial_Slave2Left_4.setNotchesVisible(True)
        self.dial_Slave2Left_4.setObjectName(_fromUtf8("dial_Slave2Left_4"))
        self.dial_Slave2Right_4 = QtGui.QDial(self.frame_12)
        self.dial_Slave2Right_4.setGeometry(QtCore.QRect(80, 120, 61, 50))
        self.dial_Slave2Right_4.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_Slave2Right_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dial_Slave2Right_4.setMinimum(0)
        self.dial_Slave2Right_4.setMaximum(7)
        self.dial_Slave2Right_4.setPageStep(8)
        self.dial_Slave2Right_4.setWrapping(False)
        self.dial_Slave2Right_4.setNotchesVisible(True)
        self.dial_Slave2Right_4.setObjectName(_fromUtf8("dial_Slave2Right_4"))
        self.verticalLayout_3 = QtGui.QWidget(self.tab_slave2)
        self.verticalLayout_3.setGeometry(QtCore.QRect(10, 210, 160, 284))
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self._4 = QtGui.QVBoxLayout(self.verticalLayout_3)
        self._4.setObjectName(_fromUtf8("_4"))
        self.radioButton_Slave2Digital_1 = QtGui.QRadioButton(self.verticalLayout_3)
        self.radioButton_Slave2Digital_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_Slave2Digital_1.setCheckable(False)
        self.radioButton_Slave2Digital_1.setChecked(False)
        self.radioButton_Slave2Digital_1.setAutoExclusive(False)
        self.radioButton_Slave2Digital_1.setObjectName(_fromUtf8("radioButton_Slave2Digital_1"))
        self._4.addWidget(self.radioButton_Slave2Digital_1)
        self.radioButton_Slave2Digital_2 = QtGui.QRadioButton(self.verticalLayout_3)
        self.radioButton_Slave2Digital_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_Slave2Digital_2.setCheckable(False)
        self.radioButton_Slave2Digital_2.setAutoExclusive(False)
        self.radioButton_Slave2Digital_2.setObjectName(_fromUtf8("radioButton_Slave2Digital_2"))
        self._4.addWidget(self.radioButton_Slave2Digital_2)
        self.radioButton_Slave2Digital_3 = QtGui.QRadioButton(self.verticalLayout_3)
        self.radioButton_Slave2Digital_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_Slave2Digital_3.setCheckable(False)
        self.radioButton_Slave2Digital_3.setAutoExclusive(False)
        self.radioButton_Slave2Digital_3.setObjectName(_fromUtf8("radioButton_Slave2Digital_3"))
        self._4.addWidget(self.radioButton_Slave2Digital_3)
        self.radioButton_Slave2Digital_4 = QtGui.QRadioButton(self.verticalLayout_3)
        self.radioButton_Slave2Digital_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_Slave2Digital_4.setCheckable(False)
        self.radioButton_Slave2Digital_4.setAutoExclusive(False)
        self.radioButton_Slave2Digital_4.setObjectName(_fromUtf8("radioButton_Slave2Digital_4"))
        self._4.addWidget(self.radioButton_Slave2Digital_4)
        self.radioButton_Slave2Digital_5 = QtGui.QRadioButton(self.verticalLayout_3)
        self.radioButton_Slave2Digital_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_Slave2Digital_5.setCheckable(False)
        self.radioButton_Slave2Digital_5.setAutoExclusive(False)
        self.radioButton_Slave2Digital_5.setObjectName(_fromUtf8("radioButton_Slave2Digital_5"))
        self._4.addWidget(self.radioButton_Slave2Digital_5)
        self.radioButton_Slave2Digital_6 = QtGui.QRadioButton(self.verticalLayout_3)
        self.radioButton_Slave2Digital_6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_Slave2Digital_6.setCheckable(False)
        self.radioButton_Slave2Digital_6.setAutoExclusive(False)
        self.radioButton_Slave2Digital_6.setObjectName(_fromUtf8("radioButton_Slave2Digital_6"))
        self._4.addWidget(self.radioButton_Slave2Digital_6)
        self.radioButton_Slave2Digital_7 = QtGui.QRadioButton(self.verticalLayout_3)
        self.radioButton_Slave2Digital_7.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_Slave2Digital_7.setCheckable(False)
        self.radioButton_Slave2Digital_7.setAutoExclusive(False)
        self.radioButton_Slave2Digital_7.setObjectName(_fromUtf8("radioButton_Slave2Digital_7"))
        self._4.addWidget(self.radioButton_Slave2Digital_7)
        self.radioButton_Slave2Digital_8 = QtGui.QRadioButton(self.verticalLayout_3)
        self.radioButton_Slave2Digital_8.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_Slave2Digital_8.setCheckable(False)
        self.radioButton_Slave2Digital_8.setAutoExclusive(False)
        self.radioButton_Slave2Digital_8.setObjectName(_fromUtf8("radioButton_Slave2Digital_8"))
        self._4.addWidget(self.radioButton_Slave2Digital_8)
        self.lcdNumber_AX_Slave2 = QtGui.QLCDNumber(self.tab_slave2)
        self.lcdNumber_AX_Slave2.setGeometry(QtCore.QRect(200, 210, 64, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(20, 19, 18))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 19, 18))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.lcdNumber_AX_Slave2.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lcdNumber_AX_Slave2.setFont(font)
        self.lcdNumber_AX_Slave2.setNumDigits(4)
        self.lcdNumber_AX_Slave2.setProperty("value", 0.0)
        self.lcdNumber_AX_Slave2.setProperty("intValue", 0)
        self.lcdNumber_AX_Slave2.setObjectName(_fromUtf8("lcdNumber_AX_Slave2"))
        self.label_17 = QtGui.QLabel(self.tab_slave2)
        self.label_17.setGeometry(QtCore.QRect(200, 240, 60, 18))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.tab_slave2)
        self.label_18.setGeometry(QtCore.QRect(60, 190, 60, 18))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_19 = QtGui.QLabel(self.tab_slave2)
        self.label_19.setGeometry(QtCore.QRect(190, 190, 71, 18))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.tab_slave2)
        self.label_20.setGeometry(QtCore.QRect(330, 190, 71, 18))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(self.tab_slave2)
        self.label_21.setGeometry(QtCore.QRect(470, 190, 71, 18))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.progressBar_Voltage_Slave2 = QtGui.QProgressBar(self.tab_slave2)
        self.progressBar_Voltage_Slave2.setGeometry(QtCore.QRect(300, 210, 161, 23))
        self.progressBar_Voltage_Slave2.setMaximum(12)
        self.progressBar_Voltage_Slave2.setProperty("value", 0)
        self.progressBar_Voltage_Slave2.setObjectName(_fromUtf8("progressBar_Voltage_Slave2"))
        self.label_30 = QtGui.QLabel(self.tab_slave2)
        self.label_30.setGeometry(QtCore.QRect(300, 240, 60, 18))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.checkBoxConnection_Slave2 = QtGui.QCheckBox(self.tab_slave2)
        self.checkBoxConnection_Slave2.setGeometry(QtCore.QRect(400, 350, 121, 23))
        self.checkBoxConnection_Slave2.setObjectName(_fromUtf8("checkBoxConnection_Slave2"))
        self.tabWidget.addTab(self.tab_slave2, _fromUtf8(""))
        self.tab_slave3 = QtGui.QWidget()
        self.tab_slave3.setObjectName(_fromUtf8("tab_slave3"))
        self.pushButton_Stop_4 = QtGui.QPushButton(self.tab_slave3)
        self.pushButton_Stop_4.setGeometry(QtCore.QRect(420, 410, 83, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(151, 150, 149))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.pushButton_Stop_4.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Stop_4.setFont(font)
        self.pushButton_Stop_4.setObjectName(_fromUtf8("pushButton_Stop_4"))
        self.frame_13 = QtGui.QFrame(self.tab_slave3)
        self.frame_13.setGeometry(QtCore.QRect(10, 10, 141, 181))
        self.frame_13.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_13.setObjectName(_fromUtf8("frame_13"))
        self.dial_Slave3Both_1 = QtGui.QDial(self.frame_13)
        self.dial_Slave3Both_1.setGeometry(QtCore.QRect(20, 10, 100, 100))
        self.dial_Slave3Both_1.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_Slave3Both_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dial_Slave3Both_1.setMinimum(-7)
        self.dial_Slave3Both_1.setMaximum(7)
        self.dial_Slave3Both_1.setPageStep(8)
        self.dial_Slave3Both_1.setWrapping(False)
        self.dial_Slave3Both_1.setNotchesVisible(True)
        self.dial_Slave3Both_1.setObjectName(_fromUtf8("dial_Slave3Both_1"))
        self.dial_Slave3Left_1 = QtGui.QDial(self.frame_13)
        self.dial_Slave3Left_1.setGeometry(QtCore.QRect(10, 120, 61, 50))
        self.dial_Slave3Left_1.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_Slave3Left_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dial_Slave3Left_1.setMinimum(0)
        self.dial_Slave3Left_1.setMaximum(7)
        self.dial_Slave3Left_1.setPageStep(8)
        self.dial_Slave3Left_1.setWrapping(False)
        self.dial_Slave3Left_1.setNotchesVisible(True)
        self.dial_Slave3Left_1.setObjectName(_fromUtf8("dial_Slave3Left_1"))
        self.dial_Slave3Right_1 = QtGui.QDial(self.frame_13)
        self.dial_Slave3Right_1.setGeometry(QtCore.QRect(80, 120, 61, 50))
        self.dial_Slave3Right_1.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_Slave3Right_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dial_Slave3Right_1.setMinimum(0)
        self.dial_Slave3Right_1.setMaximum(7)
        self.dial_Slave3Right_1.setPageStep(8)
        self.dial_Slave3Right_1.setWrapping(False)
        self.dial_Slave3Right_1.setNotchesVisible(True)
        self.dial_Slave3Right_1.setObjectName(_fromUtf8("dial_Slave3Right_1"))
        self.frame_14 = QtGui.QFrame(self.tab_slave3)
        self.frame_14.setGeometry(QtCore.QRect(150, 10, 141, 181))
        self.frame_14.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_14.setObjectName(_fromUtf8("frame_14"))
        self.dial_Slave3Both_2 = QtGui.QDial(self.frame_14)
        self.dial_Slave3Both_2.setGeometry(QtCore.QRect(20, 10, 100, 100))
        self.dial_Slave3Both_2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_Slave3Both_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dial_Slave3Both_2.setMinimum(-7)
        self.dial_Slave3Both_2.setMaximum(7)
        self.dial_Slave3Both_2.setPageStep(8)
        self.dial_Slave3Both_2.setWrapping(False)
        self.dial_Slave3Both_2.setNotchesVisible(True)
        self.dial_Slave3Both_2.setObjectName(_fromUtf8("dial_Slave3Both_2"))
        self.dial_Slave3Left_2 = QtGui.QDial(self.frame_14)
        self.dial_Slave3Left_2.setGeometry(QtCore.QRect(10, 120, 61, 50))
        self.dial_Slave3Left_2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_Slave3Left_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dial_Slave3Left_2.setMinimum(0)
        self.dial_Slave3Left_2.setMaximum(7)
        self.dial_Slave3Left_2.setPageStep(8)
        self.dial_Slave3Left_2.setWrapping(False)
        self.dial_Slave3Left_2.setNotchesVisible(True)
        self.dial_Slave3Left_2.setObjectName(_fromUtf8("dial_Slave3Left_2"))
        self.dial_Slave3Right_2 = QtGui.QDial(self.frame_14)
        self.dial_Slave3Right_2.setGeometry(QtCore.QRect(80, 120, 61, 50))
        self.dial_Slave3Right_2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_Slave3Right_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dial_Slave3Right_2.setMinimum(0)
        self.dial_Slave3Right_2.setMaximum(7)
        self.dial_Slave3Right_2.setPageStep(8)
        self.dial_Slave3Right_2.setWrapping(False)
        self.dial_Slave3Right_2.setNotchesVisible(True)
        self.dial_Slave3Right_2.setObjectName(_fromUtf8("dial_Slave3Right_2"))
        self.frame_15 = QtGui.QFrame(self.tab_slave3)
        self.frame_15.setGeometry(QtCore.QRect(290, 10, 141, 181))
        self.frame_15.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_15.setObjectName(_fromUtf8("frame_15"))
        self.dial_Slave3Both_3 = QtGui.QDial(self.frame_15)
        self.dial_Slave3Both_3.setGeometry(QtCore.QRect(20, 10, 100, 100))
        self.dial_Slave3Both_3.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_Slave3Both_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dial_Slave3Both_3.setMinimum(-7)
        self.dial_Slave3Both_3.setMaximum(7)
        self.dial_Slave3Both_3.setPageStep(8)
        self.dial_Slave3Both_3.setWrapping(False)
        self.dial_Slave3Both_3.setNotchesVisible(True)
        self.dial_Slave3Both_3.setObjectName(_fromUtf8("dial_Slave3Both_3"))
        self.dial_Slave3Left_3 = QtGui.QDial(self.frame_15)
        self.dial_Slave3Left_3.setGeometry(QtCore.QRect(10, 120, 61, 50))
        self.dial_Slave3Left_3.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_Slave3Left_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dial_Slave3Left_3.setMinimum(0)
        self.dial_Slave3Left_3.setMaximum(7)
        self.dial_Slave3Left_3.setPageStep(8)
        self.dial_Slave3Left_3.setWrapping(False)
        self.dial_Slave3Left_3.setNotchesVisible(True)
        self.dial_Slave3Left_3.setObjectName(_fromUtf8("dial_Slave3Left_3"))
        self.dial_Slave3Right_3 = QtGui.QDial(self.frame_15)
        self.dial_Slave3Right_3.setGeometry(QtCore.QRect(80, 120, 61, 50))
        self.dial_Slave3Right_3.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_Slave3Right_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dial_Slave3Right_3.setMinimum(0)
        self.dial_Slave3Right_3.setMaximum(7)
        self.dial_Slave3Right_3.setPageStep(8)
        self.dial_Slave3Right_3.setWrapping(False)
        self.dial_Slave3Right_3.setNotchesVisible(True)
        self.dial_Slave3Right_3.setObjectName(_fromUtf8("dial_Slave3Right_3"))
        self.frame_16 = QtGui.QFrame(self.tab_slave3)
        self.frame_16.setGeometry(QtCore.QRect(430, 10, 141, 181))
        self.frame_16.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_16.setObjectName(_fromUtf8("frame_16"))
        self.dial_Slave3Both_4 = QtGui.QDial(self.frame_16)
        self.dial_Slave3Both_4.setGeometry(QtCore.QRect(20, 10, 100, 100))
        self.dial_Slave3Both_4.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_Slave3Both_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dial_Slave3Both_4.setMinimum(-7)
        self.dial_Slave3Both_4.setMaximum(7)
        self.dial_Slave3Both_4.setPageStep(8)
        self.dial_Slave3Both_4.setWrapping(False)
        self.dial_Slave3Both_4.setNotchesVisible(True)
        self.dial_Slave3Both_4.setObjectName(_fromUtf8("dial_Slave3Both_4"))
        self.dial_Slave3Left_4 = QtGui.QDial(self.frame_16)
        self.dial_Slave3Left_4.setGeometry(QtCore.QRect(10, 120, 61, 50))
        self.dial_Slave3Left_4.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_Slave3Left_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dial_Slave3Left_4.setMinimum(0)
        self.dial_Slave3Left_4.setMaximum(7)
        self.dial_Slave3Left_4.setPageStep(8)
        self.dial_Slave3Left_4.setWrapping(False)
        self.dial_Slave3Left_4.setNotchesVisible(True)
        self.dial_Slave3Left_4.setObjectName(_fromUtf8("dial_Slave3Left_4"))
        self.dial_Slave3Right_4 = QtGui.QDial(self.frame_16)
        self.dial_Slave3Right_4.setGeometry(QtCore.QRect(80, 120, 61, 50))
        self.dial_Slave3Right_4.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_Slave3Right_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dial_Slave3Right_4.setMinimum(0)
        self.dial_Slave3Right_4.setMaximum(7)
        self.dial_Slave3Right_4.setPageStep(8)
        self.dial_Slave3Right_4.setWrapping(False)
        self.dial_Slave3Right_4.setNotchesVisible(True)
        self.dial_Slave3Right_4.setObjectName(_fromUtf8("dial_Slave3Right_4"))
        self.verticalLayout_4 = QtGui.QWidget(self.tab_slave3)
        self.verticalLayout_4.setGeometry(QtCore.QRect(10, 210, 160, 284))
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self._6 = QtGui.QVBoxLayout(self.verticalLayout_4)
        self._6.setObjectName(_fromUtf8("_6"))
        self.radioButton_Slave3Digital_1 = QtGui.QRadioButton(self.verticalLayout_4)
        self.radioButton_Slave3Digital_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_Slave3Digital_1.setCheckable(False)
        self.radioButton_Slave3Digital_1.setChecked(False)
        self.radioButton_Slave3Digital_1.setAutoExclusive(False)
        self.radioButton_Slave3Digital_1.setObjectName(_fromUtf8("radioButton_Slave3Digital_1"))
        self._6.addWidget(self.radioButton_Slave3Digital_1)
        self.radioButton_Slave3Digital_2 = QtGui.QRadioButton(self.verticalLayout_4)
        self.radioButton_Slave3Digital_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_Slave3Digital_2.setCheckable(False)
        self.radioButton_Slave3Digital_2.setAutoExclusive(False)
        self.radioButton_Slave3Digital_2.setObjectName(_fromUtf8("radioButton_Slave3Digital_2"))
        self._6.addWidget(self.radioButton_Slave3Digital_2)
        self.radioButton_Slave3Digital_3 = QtGui.QRadioButton(self.verticalLayout_4)
        self.radioButton_Slave3Digital_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_Slave3Digital_3.setCheckable(False)
        self.radioButton_Slave3Digital_3.setAutoExclusive(False)
        self.radioButton_Slave3Digital_3.setObjectName(_fromUtf8("radioButton_Slave3Digital_3"))
        self._6.addWidget(self.radioButton_Slave3Digital_3)
        self.radioButton_Slave3Digital_4 = QtGui.QRadioButton(self.verticalLayout_4)
        self.radioButton_Slave3Digital_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_Slave3Digital_4.setCheckable(False)
        self.radioButton_Slave3Digital_4.setAutoExclusive(False)
        self.radioButton_Slave3Digital_4.setObjectName(_fromUtf8("radioButton_Slave3Digital_4"))
        self._6.addWidget(self.radioButton_Slave3Digital_4)
        self.radioButton_Slave3Digital_5 = QtGui.QRadioButton(self.verticalLayout_4)
        self.radioButton_Slave3Digital_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_Slave3Digital_5.setCheckable(False)
        self.radioButton_Slave3Digital_5.setAutoExclusive(False)
        self.radioButton_Slave3Digital_5.setObjectName(_fromUtf8("radioButton_Slave3Digital_5"))
        self._6.addWidget(self.radioButton_Slave3Digital_5)
        self.radioButton_Slave3Digital_6 = QtGui.QRadioButton(self.verticalLayout_4)
        self.radioButton_Slave3Digital_6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_Slave3Digital_6.setCheckable(False)
        self.radioButton_Slave3Digital_6.setAutoExclusive(False)
        self.radioButton_Slave3Digital_6.setObjectName(_fromUtf8("radioButton_Slave3Digital_6"))
        self._6.addWidget(self.radioButton_Slave3Digital_6)
        self.radioButton_Slave3Digital_7 = QtGui.QRadioButton(self.verticalLayout_4)
        self.radioButton_Slave3Digital_7.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_Slave3Digital_7.setCheckable(False)
        self.radioButton_Slave3Digital_7.setAutoExclusive(False)
        self.radioButton_Slave3Digital_7.setObjectName(_fromUtf8("radioButton_Slave3Digital_7"))
        self._6.addWidget(self.radioButton_Slave3Digital_7)
        self.radioButton_Slave3Digital_8 = QtGui.QRadioButton(self.verticalLayout_4)
        self.radioButton_Slave3Digital_8.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_Slave3Digital_8.setCheckable(False)
        self.radioButton_Slave3Digital_8.setAutoExclusive(False)
        self.radioButton_Slave3Digital_8.setObjectName(_fromUtf8("radioButton_Slave3Digital_8"))
        self._6.addWidget(self.radioButton_Slave3Digital_8)
        self.lcdNumber_AX_Slave3 = QtGui.QLCDNumber(self.tab_slave3)
        self.lcdNumber_AX_Slave3.setGeometry(QtCore.QRect(200, 210, 64, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(20, 19, 18))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 19, 18))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.lcdNumber_AX_Slave3.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lcdNumber_AX_Slave3.setFont(font)
        self.lcdNumber_AX_Slave3.setNumDigits(4)
        self.lcdNumber_AX_Slave3.setProperty("value", 0.0)
        self.lcdNumber_AX_Slave3.setProperty("intValue", 0)
        self.lcdNumber_AX_Slave3.setObjectName(_fromUtf8("lcdNumber_AX_Slave3"))
        self.label_22 = QtGui.QLabel(self.tab_slave3)
        self.label_22.setGeometry(QtCore.QRect(200, 240, 60, 18))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_23 = QtGui.QLabel(self.tab_slave3)
        self.label_23.setGeometry(QtCore.QRect(60, 190, 60, 18))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtGui.QLabel(self.tab_slave3)
        self.label_24.setGeometry(QtCore.QRect(190, 190, 71, 18))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_25 = QtGui.QLabel(self.tab_slave3)
        self.label_25.setGeometry(QtCore.QRect(330, 190, 71, 18))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_26 = QtGui.QLabel(self.tab_slave3)
        self.label_26.setGeometry(QtCore.QRect(470, 190, 71, 18))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.progressBar_Voltage_Slave3 = QtGui.QProgressBar(self.tab_slave3)
        self.progressBar_Voltage_Slave3.setGeometry(QtCore.QRect(300, 210, 161, 23))
        self.progressBar_Voltage_Slave3.setMaximum(12)
        self.progressBar_Voltage_Slave3.setProperty("value", 1)
        self.progressBar_Voltage_Slave3.setObjectName(_fromUtf8("progressBar_Voltage_Slave3"))
        self.label_31 = QtGui.QLabel(self.tab_slave3)
        self.label_31.setGeometry(QtCore.QRect(300, 240, 60, 18))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.checkBoxConnection_Slave3 = QtGui.QCheckBox(self.tab_slave3)
        self.checkBoxConnection_Slave3.setGeometry(QtCore.QRect(400, 350, 121, 23))
        self.checkBoxConnection_Slave3.setObjectName(_fromUtf8("checkBoxConnection_Slave3"))
        self.tabWidget.addTab(self.tab_slave3, _fromUtf8(""))
        diag.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(diag)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 580, 19))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        diag.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(diag)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        diag.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(diag)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionClose = QtGui.QAction(diag)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionClose_Interface = QtGui.QAction(diag)
        self.actionClose_Interface.setObjectName(_fromUtf8("actionClose_Interface"))
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionClose_Interface)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(diag)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionClose, QtCore.SIGNAL(_fromUtf8("triggered()")), diag.close)
        QtCore.QMetaObject.connectSlotsByName(diag)

    def retranslateUi(self, diag):
        diag.setWindowTitle(_translate("diag", "Diagnose ft Interface", None))
        self.dial_MainBoth_1.setToolTip(_translate("diag", "Motor 1", None))
        self.dial_MainLeft_1.setToolTip(_translate("diag", "Output 1", None))
        self.dial_MainRight_1.setToolTip(_translate("diag", "Output 2", None))
        self.dial_MainBoth_2.setToolTip(_translate("diag", "Motor 2", None))
        self.dial_MainLeft_2.setToolTip(_translate("diag", "Output 3", None))
        self.dial_MainRight_2.setToolTip(_translate("diag", "Output 4", None))
        self.dial_MainBoth_3.setToolTip(_translate("diag", "Motor 3", None))
        self.dial_MainLeft_3.setToolTip(_translate("diag", "Output 5", None))
        self.dial_MainRight_3.setToolTip(_translate("diag", "Output 6", None))
        self.dial_MainBoth_4.setToolTip(_translate("diag", "Motor 4", None))
        self.dial_MainLeft_4.setToolTip(_translate("diag", "Output 7", None))
        self.dial_MainRight_4.setToolTip(_translate("diag", "Output 8", None))
        self.radioButton_MainDigital_1.setText(_translate("diag", "Input 1", None))
        self.radioButton_MainDigital_2.setText(_translate("diag", "Input 2", None))
        self.radioButton_MainDigital_3.setText(_translate("diag", "Input 3", None))
        self.radioButton_MainDigital_4.setText(_translate("diag", "Input 4", None))
        self.radioButton_MainDigital_5.setText(_translate("diag", "Input 5", None))
        self.radioButton_MainDigital_6.setText(_translate("diag", "Input 6", None))
        self.radioButton_MainDigital_7.setText(_translate("diag", "Input 7", None))
        self.radioButton_MainDigital_8.setText(_translate("diag", "Input 8", None))
        self.progressBar_Voltage.setToolTip(_translate("diag", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">AV</p></body></html>", None))
        self.progressBar_Voltage.setFormat(_translate("diag", "%v", None))
        self.lcdNumber_AX.setToolTip(_translate("diag", "AX", None))
        self.lcdNumber_AY.setToolTip(_translate("diag", "AY", None))
        self.lcdNumber_A1.setToolTip(_translate("diag", "A1", None))
        self.lcdNumber_A2.setToolTip(_translate("diag", "A2", None))
        self.lcdNumber_AZ.setToolTip(_translate("diag", "AZ", None))
        self.lcdNumber_IR.setToolTip(_translate("diag", "IR", None))
        self.label.setText(_translate("diag", "IR", None))
        self.label_2.setText(_translate("diag", "AX", None))
        self.label_3.setText(_translate("diag", "AY", None))
        self.label_4.setText(_translate("diag", "AZ", None))
        self.label_5.setText(_translate("diag", "A1", None))
        self.label_6.setText(_translate("diag", "A2", None))
        self.label_7.setText(_translate("diag", "AV", None))
        self.label_8.setText(_translate("diag", "Motor 1", None))
        self.label_9.setText(_translate("diag", "Motor 2", None))
        self.label_10.setText(_translate("diag", "Motor 3", None))
        self.label_11.setText(_translate("diag", "Motor 4", None))
        self.pushButton_Stop.setText(_translate("diag", "STOP", None))
        self.lcdNumber_D1.setToolTip(_translate("diag", "A1", None))
        self.lcdNumber_D2.setToolTip(_translate("diag", "A1", None))
        self.label_27.setText(_translate("diag", "D1", None))
        self.label_28.setText(_translate("diag", "D2", None))
        self.checkBoxConnection_Main.setText(_translate("diag", "Connection", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_main), _translate("diag", "Main", None))
        self.dial_Slave1Both_1.setToolTip(_translate("diag", "Motor 1", None))
        self.dial_Slave1Left_1.setToolTip(_translate("diag", "Output 1", None))
        self.dial_Slave1Right_1.setToolTip(_translate("diag", "Output 2", None))
        self.dial_Slave1Both_2.setToolTip(_translate("diag", "Motor 2", None))
        self.dial_Slave1Left_2.setToolTip(_translate("diag", "Output 3", None))
        self.dial_Slave1Right_2.setToolTip(_translate("diag", "Output 4", None))
        self.dial_Slave1Both_3.setToolTip(_translate("diag", "Motor 3", None))
        self.dial_Slave1Left_3.setToolTip(_translate("diag", "Output 5", None))
        self.dial_Slave1Right_3.setToolTip(_translate("diag", "Output 6", None))
        self.dial_Slave1Both_4.setToolTip(_translate("diag", "Motor 4", None))
        self.dial_Slave1Left_4.setToolTip(_translate("diag", "Output 7", None))
        self.dial_Slave1Right_4.setToolTip(_translate("diag", "Output 8", None))
        self.radioButton_Slave1Digital_1.setText(_translate("diag", "Input 1", None))
        self.radioButton_Slave1Digital_2.setText(_translate("diag", "Input 2", None))
        self.radioButton_Slave1Digital_3.setText(_translate("diag", "Input 3", None))
        self.radioButton_Slave1Digital_4.setText(_translate("diag", "Input 4", None))
        self.radioButton_Slave1Digital_5.setText(_translate("diag", "Input 5", None))
        self.radioButton_Slave1Digital_6.setText(_translate("diag", "Input 6", None))
        self.radioButton_Slave1Digital_7.setText(_translate("diag", "Input 7", None))
        self.radioButton_Slave1Digital_8.setText(_translate("diag", "Input 8", None))
        self.lcdNumber_AX_Slave1.setToolTip(_translate("diag", "AX", None))
        self.label_12.setText(_translate("diag", "AX", None))
        self.pushButton_Stop_2.setText(_translate("diag", "STOP", None))
        self.label_13.setText(_translate("diag", "Motor 1", None))
        self.label_14.setText(_translate("diag", "Motor 2", None))
        self.label_15.setText(_translate("diag", "Motor 3", None))
        self.label_16.setText(_translate("diag", "Motor 4", None))
        self.progressBar_Voltage_Slave1.setToolTip(_translate("diag", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">AV</p></body></html>", None))
        self.progressBar_Voltage_Slave1.setFormat(_translate("diag", "%v", None))
        self.label_29.setText(_translate("diag", "AV", None))
        self.checkBoxConnection_Slave1.setText(_translate("diag", "Connection", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_slave1), _translate("diag", "Slave 1", None))
        self.pushButton_Stop_3.setText(_translate("diag", "STOP", None))
        self.dial_Slave2Both_1.setToolTip(_translate("diag", "Motor 1", None))
        self.dial_Slave2Left_1.setToolTip(_translate("diag", "Output 1", None))
        self.dial_Slave2Right_1.setToolTip(_translate("diag", "Output 2", None))
        self.dial_Slave2Both_2.setToolTip(_translate("diag", "Motor 2", None))
        self.dial_Slave2Left_2.setToolTip(_translate("diag", "Output 3", None))
        self.dial_Slave2Right_2.setToolTip(_translate("diag", "Output 4", None))
        self.dial_Slave2Both_3.setToolTip(_translate("diag", "Motor 3", None))
        self.dial_Slave2Left_3.setToolTip(_translate("diag", "Output 5", None))
        self.dial_Slave2Right_3.setToolTip(_translate("diag", "Output 6", None))
        self.dial_Slave2Both_4.setToolTip(_translate("diag", "Motor 4", None))
        self.dial_Slave2Left_4.setToolTip(_translate("diag", "Output 7", None))
        self.dial_Slave2Right_4.setToolTip(_translate("diag", "Output 8", None))
        self.radioButton_Slave2Digital_1.setText(_translate("diag", "Input 1", None))
        self.radioButton_Slave2Digital_2.setText(_translate("diag", "Input 2", None))
        self.radioButton_Slave2Digital_3.setText(_translate("diag", "Input 3", None))
        self.radioButton_Slave2Digital_4.setText(_translate("diag", "Input 4", None))
        self.radioButton_Slave2Digital_5.setText(_translate("diag", "Input 5", None))
        self.radioButton_Slave2Digital_6.setText(_translate("diag", "Input 6", None))
        self.radioButton_Slave2Digital_7.setText(_translate("diag", "Input 7", None))
        self.radioButton_Slave2Digital_8.setText(_translate("diag", "Input 8", None))
        self.lcdNumber_AX_Slave2.setToolTip(_translate("diag", "AX", None))
        self.label_17.setText(_translate("diag", "AX", None))
        self.label_18.setText(_translate("diag", "Motor 1", None))
        self.label_19.setText(_translate("diag", "Motor 2", None))
        self.label_20.setText(_translate("diag", "Motor 3", None))
        self.label_21.setText(_translate("diag", "Motor 4", None))
        self.progressBar_Voltage_Slave2.setToolTip(_translate("diag", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">AV</p></body></html>", None))
        self.progressBar_Voltage_Slave2.setFormat(_translate("diag", "%v", None))
        self.label_30.setText(_translate("diag", "AV", None))
        self.checkBoxConnection_Slave2.setText(_translate("diag", "Connection", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_slave2), _translate("diag", "Slave 2", None))
        self.pushButton_Stop_4.setText(_translate("diag", "STOP", None))
        self.dial_Slave3Both_1.setToolTip(_translate("diag", "Motor 1", None))
        self.dial_Slave3Left_1.setToolTip(_translate("diag", "Output 1", None))
        self.dial_Slave3Right_1.setToolTip(_translate("diag", "Output 2", None))
        self.dial_Slave3Both_2.setToolTip(_translate("diag", "Motor 2", None))
        self.dial_Slave3Left_2.setToolTip(_translate("diag", "Output 3", None))
        self.dial_Slave3Right_2.setToolTip(_translate("diag", "Output 4", None))
        self.dial_Slave3Both_3.setToolTip(_translate("diag", "Motor 3", None))
        self.dial_Slave3Left_3.setToolTip(_translate("diag", "Output 5", None))
        self.dial_Slave3Right_3.setToolTip(_translate("diag", "Output 6", None))
        self.dial_Slave3Both_4.setToolTip(_translate("diag", "Motor 4", None))
        self.dial_Slave3Left_4.setToolTip(_translate("diag", "Output 7", None))
        self.dial_Slave3Right_4.setToolTip(_translate("diag", "Output 8", None))
        self.radioButton_Slave3Digital_1.setText(_translate("diag", "Input 1", None))
        self.radioButton_Slave3Digital_2.setText(_translate("diag", "Input 2", None))
        self.radioButton_Slave3Digital_3.setText(_translate("diag", "Input 3", None))
        self.radioButton_Slave3Digital_4.setText(_translate("diag", "Input 4", None))
        self.radioButton_Slave3Digital_5.setText(_translate("diag", "Input 5", None))
        self.radioButton_Slave3Digital_6.setText(_translate("diag", "Input 6", None))
        self.radioButton_Slave3Digital_7.setText(_translate("diag", "Input 7", None))
        self.radioButton_Slave3Digital_8.setText(_translate("diag", "Input 8", None))
        self.lcdNumber_AX_Slave3.setToolTip(_translate("diag", "AX", None))
        self.label_22.setText(_translate("diag", "AX", None))
        self.label_23.setText(_translate("diag", "Motor 1", None))
        self.label_24.setText(_translate("diag", "Motor 2", None))
        self.label_25.setText(_translate("diag", "Motor 3", None))
        self.label_26.setText(_translate("diag", "Motor 4", None))
        self.progressBar_Voltage_Slave3.setToolTip(_translate("diag", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">AV</p></body></html>", None))
        self.progressBar_Voltage_Slave3.setFormat(_translate("diag", "%v", None))
        self.label_31.setText(_translate("diag", "AV", None))
        self.checkBoxConnection_Slave3.setText(_translate("diag", "Connection", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_slave3), _translate("diag", "Slave 3", None))
        self.menuFile.setTitle(_translate("diag", "File", None))
        self.actionOpen.setText(_translate("diag", "Open Interface", None))
        self.actionClose.setText(_translate("diag", "Close Window", None))
        self.actionClose_Interface.setText(_translate("diag", "Close Interface", None))

