libft: lib/libft.c File Reference
lib/libft.c File Reference
Functions
long int GetLibVersion ()
Returns lib version.
char * GetLibVersionStrg ()
Returns lib version.
long int InitFtLib ()
Library initialization (dummy).
long int InitFtUsbDeviceList ()
Initiates and scans the USB bus.
unsigned int GetNumFtUsbDevice ()
Get the count of found ft Interfaces over USB.
FT_HANDLE GetFtUsbDeviceHandle (unsigned char Num)
Gets the handle to a ft USB device.
FT_HANDLE GetFtUsbDeviceHandleSerialNr (long int dwSN, long int dwTyp)
Gets the handle to a ft USB device with a specific serial number.
FT_HANDLE OpenFtCommDevice (char *sDevice, long int dwTyp, long int dwZyklus)
Gets the handle to a ft serial device.
long int GetFtDeviceTyp (FT_HANDLE hFt)
Returns type of the interface.
long int GetFtDeviceTypeString (FT_HANDLE hFt, char *dest, int len)
Returns a string that identifies the interface with human words.
long int OpenFtUsbDevice (FT_HANDLE hFt)
Opens this USB device.
long int CloseFtDevice (FT_HANDLE hFt)
Close the ft Device.
long int CloseFtLib ()
Library deinitialization (dummy).
long int IsFtLibInit ()
Check for Library initialization (dummy).
long int ResetFtTransfer (FT_HANDLE hFt)
reset outputs
long int StartFtTransferArea (FT_HANDLE hFt, NOTIFICATION_EVENTS *ignored)
Starts the communication thread.
long int StartFtTransferAreaWithCommunication (FT_HANDLE hFt, NOTIFICATION_EVENTS *ignored)
Starts the communication thread.
FT_TRANSFER_AREA * GetFtTransferAreaAddress (FT_HANDLE hFt)
Get the transfer area.
long int StopFtTransferArea (FT_HANDLE hFt)
Stops the communication thread.
long int IsFtTransferActiv (FT_HANDLE hFt)
check if transfer is active.
long int DownloadFtProgram (FT_HANDLE hFt, long int dwMemBlock, unsigned char *pbArray, long int dwSize, long int dwParameter, unsigned char *pbName, long int dwNameLen)
Upload a program to the interface.
long int StartFtProgram (FT_HANDLE hFt, long int dwMemBlock)
Start a program.
long int StopFtProgram (FT_HANDLE hFt)
Stop a program.
long int DeleteFtProgram (FT_HANDLE hFt, long int dwMemBlock)
Delete a program.
long int SetFtProgramActiv (FT_HANDLE hFt, long int dwMemBlock)
Activate a program.
long int GetFtProgramName (FT_HANDLE hFt, long int dwMemBlock, long int dwSize, void *pName)
Get the name of a program.
int GetFtStatus (FT_HANDLE hFt, int *num)
Checks if a program is running.
long int GetFtFirmware (FT_HANDLE hFt)
Get the firmware number of this interface.
char * GetFtFirmwareStrg (FT_HANDLE hFt)
Get the firmware number of this interface.
long int GetFtSerialNr (FT_HANDLE hFt)
Get the serial number of this interface.
char * GetFtSerialNrStrg (FT_HANDLE hFt)
Get the serial number of this interface.
long int CloseAllFtDevices ()
Close all ft devices.
long int SetFtDistanceSensorMode (FT_HANDLE hFt, long int dwMode, long int dwTol1, long int dwTol2, long int dwLevel1, long int dwLevel2, long int dwRepeat1, long int dwRepeat2)
Set the inputs D1 and D2 to distance oder voltage measuring.
long int SetRFMode (FT_HANDLE hFt, long int frequency, long int callSign)
Sets the frequency and call sign for a Robo Interface or RF Data Link.
long int GetRFMode (FT_HANDLE hFt, long int *frequency, long int *callSign)
Gets the frequency and call sign of a Robo Interface or RF Data Link.
long int SetRealSerial (FT_HANDLE hFt, unsigned char bOn)
Switches between the real serial and 0001 of a device.
char * GetFtManufacturerStrg (FT_HANDLE hFt)
Gets the Manufacturer of the Interface.
char * GetFtShortNameStrg (FT_HANDLE hFt)
Gets the short name of the Interface.
char * GetFtLongNameStrg (FT_HANDLE hFt)
Gets the long name of the Interface.
char IsFtInterfaceConnected (FT_HANDLE hFt)
Tells if we successfuly got a connection to the Interface.
char * GetFtLibErrorString (long int dwErrorCode, long int dwTyp)
Gets the description of an error.
Detailed Description
Copyright (C) 2007 Erik Andresen erik@vontaene.de
Open Source version of the fischertechnik ROBO Interface Library for Unix like systems
Communication is done through a "transfer area" this is constantly updated.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
Function Documentation
long int CloseAllFtDevices ()
Close all ft devices.
Dummy. Can't be supported. Only used in original library.
Returns:
Always FTLIB_ERR_NOT_SUPPORTED
long int CloseFtDevice (FT_HANDLE hFt)
Close the ft Device.
This function will close the ft Device and free its memory.
Parameters:
hFt Handle of the Device to close.
Returns:
A number < 0 on error.
Examples:
example.c.
References ft_handle_devices::device, ft_handle_devices::saveioset, ft_handle_devices::sdev, ft_handle_devices::transfer_area, _FT_TRANSFER_AREA::TransferAktiv, and ft_handle_devices::type.
Referenced by GetFtUsbDeviceHandleSerialNr().
long int CloseFtLib ()
Library deinitialization (dummy).
Dummy for compatibility. Only used in original library.
Returns:
Always FTLIB_ERR_SUCCESS
long int DeleteFtProgram (FT_HANDLE hFt, long int dwMemBlock)
Delete a program.
Will delete a program that has been uploaded to the interface.
Parameters:
hFt Handle of the Interface
dwMemBlock Destination 0 (Flash 1), 1 (Flash 2) or 2 (Ram)
Returns:
FTLIB_ERR_SUCCESS or FTLIB_ERR_IF_NO_PROGRAM
References ft_handle_devices::device, ft_handle_devices::sdev, and ft_handle_devices::type.
long int DownloadFtProgram (FT_HANDLE hFt, long int dwMemBlock, unsigned char * pbArray, long int dwSize, long int dwParameter, unsigned char * pbName, long int dwNameLen)
Upload a program to the interface.
Upload (download from the perspective of the interface) a program to the interface.
Parameters:
hFt Handle of the Interface
dwMemBlock Destination 0 (Flash 1), 1 (Flash 2) or 2 (Ram)
pbArray Pointer to the program to upload
dwSize Size of the program to upload
dwParameter 1 to Autostart this program, else 0.
pbName Name of the program to upload
dwNameLen Length of the name
Returns:
FTLIB_ERR_SUCCESS if you got lucky
References ft_handle_devices::device, and ft_handle_devices::type.
long int GetFtDeviceTyp (FT_HANDLE hFt)
Returns type of the interface.
This function will return the type of the interface that is behind the handle.
Parameters:
hFt Handle of the device
Returns:
NO_FT_DEVICE, FT_INTELLIGENT_IF, FT_INTELLIGENT_IF_SLAVE, FT_ROBO_IF_COM, FT_ROBO_IF_USB, FT_ROBO_IF_IIM, FT_ROBO_IF_OVER_RF, FT_ROBO_IO_EXTENSION or FT_ROBO_RF_DATA_LINK
References ft_handle_devices::type.
Referenced by GetFtDeviceTypeString().
long int GetFtDeviceTypeString (FT_HANDLE hFt, char * dest, int len)
Returns a string that identifies the interface with human words.
This function will give you a human readable string like "Robo Interface" you can work with.
Parameters:
hFt Handle of the device
dest Buffer we can write the string to
len Maximum length of this buffer
Returns:
FTLIB_ERR_SUCCESS or a failure
References GetFtDeviceTyp().
long int GetFtFirmware (FT_HANDLE hFt)
Get the firmware number of this interface.
Returns the firmware number of the interface squashed into a single int.
Parameters:
hFt Handle of the Interface
Returns:
Firmware number as int byte4 | byte3 | byte2 | byte1, 0 on error.
References ft_handle_devices::device, _FT_TRANSFER_AREA::RfModulNr, ft_handle_devices::sdev, ft_handle_devices::transfer_area, and ft_handle_devices::type.
Referenced by GetFtFirmwareStrg().
char* GetFtFirmwareStrg (FT_HANDLE hFt)
Get the firmware number of this interface.
Returns the firmware number of the interface with this handle. The allocated space should be freed with free() later.
Parameters:
hFt Handle of the Interface
Returns:
Pointer to a string with the firmware
References GetFtFirmware().
char* GetFtLibErrorString (long int dwErrorCode, long int dwTyp)
Gets the description of an error.
Will return a description of an error. The allocated space should be freed with free() later.
The return value is the constant as string if parameter dwTyp is 0, else a verbose description of the error.
Parameters:
dwErrorCode Error Code
dwTyp Type of the return value (see description)
Returns:
Pointer to a string (see description)
char* GetFtLongNameStrg (FT_HANDLE hFt)
Gets the long name of the Interface.
Will return the long name of a fischertechnik USB device. The allocated space should be freed with free() later.
Parameters:
hFt Handle of the Interface
Returns:
Pointer to the string with the name
References ft_handle_devices::device, and ft_handle_devices::type.
char* GetFtManufacturerStrg (FT_HANDLE hFt)
Gets the Manufacturer of the Interface.
Will return the Manufacturer of a fischertechnik USB device. The allocated space should be freed with free() later.
Parameters:
hFt Handle of the Interface
Returns:
Pointer to the string with the name
References ft_handle_devices::device, and ft_handle_devices::type.
long int GetFtProgramName (FT_HANDLE hFt, long int dwMemBlock, long int dwSize, void * pName)
Get the name of a program.
Will write the name of a program that has been uploaded to the interface to a given area.
Parameters:
hFt Handle of the Interface
dwMemBlock Destination 0 (Flash 1), 1 (Flash 2) or 2 (Ram)
pName Pointer to the area where we can store the name
dwSize Size of the area to store the name to
Returns:
FTLIB_ERR_SUCCESS or FTLIB_ERR_IF_NO_PROGRAM
References ft_handle_devices::device, ft_handle_devices::sdev, and ft_handle_devices::type.
long int GetFtSerialNr (FT_HANDLE hFt)
Get the serial number of this interface.
Returns the serial number of the interface squashed into a single int.
Parameters:
hFt Handle of the Interface
Returns:
Serial number as int byte4 | byte3 | byte2 | byte1, 0 on error.
References ft_handle_devices::device, _FT_TRANSFER_AREA::RfModulNr, ft_handle_devices::sdev, ft_handle_devices::transfer_area, and ft_handle_devices::type.
Referenced by GetFtSerialNrStrg(), and GetFtUsbDeviceHandleSerialNr().
char* GetFtSerialNrStrg (FT_HANDLE hFt)
Get the serial number of this interface.
Returns the serial number of the interface with this handle. The allocated space should be freed with free() later.
Parameters:
hFt Handle of the Interface
Returns:
Pointer to a string with the serial
References GetFtSerialNr().
char* GetFtShortNameStrg (FT_HANDLE hFt)
Gets the short name of the Interface.
Will return the short name of a fischertechnik USB device. The allocated space should be freed with free() later.
Parameters:
hFt Handle of the Interface
Returns:
Pointer to the string with the name
References ft_handle_devices::device, and ft_handle_devices::type.
int GetFtStatus (FT_HANDLE hFt, int * num)
Checks if a program is running.
Checks if a program is currently running.
Parameters:
hFt Handle of the Interface
num Area where we can store the number of the running program.
Returns:
1 if a program is running, else 0
References ft_handle_devices::device, ft_handle_devices::sdev, and ft_handle_devices::type.
FT_TRANSFER_AREA* GetFtTransferAreaAddress (FT_HANDLE hFt)
Get the transfer area.
This function will return a pointer to the transfer area of the given handle.
Parameters:
hFt Handle of the device.
Returns:
transfer area or NULL on error.
Examples:
example.c.
References ft_handle_devices::transfer_area.
FT_HANDLE GetFtUsbDeviceHandle (unsigned char Num)
Gets the handle to a ft USB device.
Get the handle for the ft USB device with this number. Passing just 0 as argument will use the first device found.
Count the interfaces with GetNumFtUsbDevice()
See also:
GetNumFtUsbDevice()
Parameters:
Num selected Interface. If unsure try 0.
Returns:
The ft device or NULL if error
Examples:
example.c.
References ft_handle_devices::dev, ft_handle_devices::device, ft_handle_devices::interface_connected, ft_handle_devices::lock, ft_handle_devices::query_time, _FT_TRANSFER_AREA::RfModulNr, ft_handle_devices::sdev, ft_handle_devices::transfer_area, _FT_TRANSFER_AREA::TransferAktiv, and ft_handle_devices::type.
Referenced by GetFtUsbDeviceHandleSerialNr().
FT_HANDLE GetFtUsbDeviceHandleSerialNr (long int dwSN, long int dwTyp)
Gets the handle to a ft USB device with a specific serial number.
Get the handle for the ft USB device with this number. Serial is 1 for most devices, unless explicitly changed in the device. Second argument can be FT_AUTO_TYPE.
Parameters:
dwSN Serial of the USB Device
dwTyp Type of the USB Device: FT_AUTO_TYPE, FT_ROBO_IF_USB, FT_ROBO_IO_EXTENSION, FT_ROBO_IF_OVER_RF or FT_ROBO_RF_DATA_LINK
Returns:
The ft device or NULL on error
References CloseFtDevice(), GetFtSerialNr(), GetFtUsbDeviceHandle(), GetNumFtUsbDevice(), OpenFtUsbDevice(), and ft_handle_devices::type.
long int GetLibVersion ()
Returns lib version.
Returns the library version.
Returns:
version as Major Minor Patch
Referenced by GetLibVersionStrg().
char* GetLibVersionStrg ()
Returns lib version.
Returns the library version. The allocated space should be freed with free() later.
Returns:
Pointer to a string with the serial
References GetLibVersion().
unsigned int GetNumFtUsbDevice ()
Get the count of found ft Interfaces over USB.
If we find a Robo RF Data Link we will count the devices attached to it instead
Returns:
Number of ft Interface devices on the USB bus found.
Examples:
example.c.
Referenced by GetFtUsbDeviceHandleSerialNr().
long int GetRFMode (FT_HANDLE hFt, long int * frequency, long int * callSign)
Gets the frequency and call sign of a Robo Interface or RF Data Link.
Sets the frequency and call sign which allows to control multiple Interfaces at one RF Data Link.
Parameters:
hFt Handle of the Interface
frequency Points to a place to store the frequency.
callSign Points to a place to store the callSign. (Value will be 0 for the RF Data Link)
Returns:
FTLIB_ERR_SUCCESS on success
References ft_handle_devices::device, ft_handle_devices::sdev, and ft_handle_devices::type.
long int InitFtLib ()
Library initialization (dummy).
Dummy for compatibility. Only used in original library.
Returns:
Always FTLIB_ERR_SUCCESS
long int InitFtUsbDeviceList ()
Initiates and scans the USB bus.
This function has to be called before any other USB action. It will set up USB basic variables and then scan the USB bus.
Returns:
Always FTLIB_ERR_SUCCESS. Not able to fail.
Examples:
example.c.
char IsFtInterfaceConnected (FT_HANDLE hFt)
Tells if we successfuly got a connection to the Interface.
Parameters:
hFt Handle of the Interface
Returns:
0 if the Interface is not connected
References ft_handle_devices::interface_connected.
long int IsFtLibInit ()
Check for Library initialization (dummy).
Dummy for compatibility. Only used in original library.
Returns:
Always FTLIB_ERR_LIB_IS_INITIALIZED since initialization is ignored in this version
long int IsFtTransferActiv (FT_HANDLE hFt)
check if transfer is active.
Check if we are currently communicating with the device.
Parameters:
hFt Handle of the Interface.
Returns:
FTLIB_ERR_THREAD_IS_RUNNING or FTLIB_ERR_THREAD_NOT_RUNNING
References ft_handle_devices::transfer_area, and _FT_TRANSFER_AREA::TransferAktiv.
FT_HANDLE OpenFtCommDevice (char * sDevice, long int dwTyp, long int dwZyklus)
Gets the handle to a ft serial device.
Get the handle for the ft Serial device at the selected serial port.
Parameters:
sDevice filename of your serial device, like /dev/ttyS0.
dwTyp Interface type. FT_INTELLIGENT_IF, FT_INTELLIGENT_IF_SLAVE or FT_ROBO_IF_COM.
dwZyklus Cycle to retrieve analog values (only II). Try 10.
Returns:
The ft device or NULL if error.
References ft_handle_devices::analogcycle, _FT_TRANSFER_AREA::BusModules, ft_handle_devices::dev, ft_handle_devices::device, ft_handle_devices::interface_connected, ft_handle_devices::lock, ft_handle_devices::newioset, ft_handle_devices::query_time, _FT_TRANSFER_AREA::RfModulNr, ft_handle_devices::saveioset, ft_handle_devices::sdev, ft_handle_devices::transfer_area, _FT_TRANSFER_AREA::TransferAktiv, and ft_handle_devices::type.
long int OpenFtUsbDevice (FT_HANDLE hFt)
Opens this USB device.
This function will try to open the ft USB device that belongs to the ft handle hFt. You can get the ft handle with GetFtUsbDeviceHandle() or GetFtUsbDeviceHandleSerialNr().
See also:
GetFtUsbDeviceHandle()
GetFtUsbDeviceHandleSerialNr()
Parameters:
hFt ft USB Device to open
Returns:
Number >= 0 on success, < 0 on error
Examples:
example.c.
References ft_handle_devices::dev, and ft_handle_devices::device.
Referenced by GetFtUsbDeviceHandleSerialNr().
long int ResetFtTransfer (FT_HANDLE hFt)
reset outputs
Will clear all outputs.
Returns:
Always FTLIB_ERR_SUCCESS
References _FT_TRANSFER_AREA::M_Main, _FT_TRANSFER_AREA::M_Sub1, _FT_TRANSFER_AREA::M_Sub2, _FT_TRANSFER_AREA::M_Sub3, and ft_handle_devices::transfer_area.
long int SetFtDistanceSensorMode (FT_HANDLE hFt, long int dwMode, long int dwTol1, long int dwTol2, long int dwLevel1, long int dwLevel2, long int dwRepeat1, long int dwRepeat2)
Set the inputs D1 and D2 to distance oder voltage measuring.
This function allows to enable the inputs D1 and D2 to measure distances. Must be called before StartFtTransferArea()
Note by Hardware Vendor: "Since the operating mode of the D1 / D2 inputs can be set by means of software, we recommend that no voltage be supplied 'directly' to these connections in order to avoid damage to the interface during software errors. Since the inputs are highly resistive, a resistance of approximately 200 Ohm - 470 Ohm should be directly connected to the D1 / D2 socket (series connection). We recommend to connect the voltage range to be measured 'behind' it."
Parameters:
hFt Handle of the Interface
dwMode Set mode to IF_DS_INPUT_VOLTAGE (measure voltage) or IF_DS_INPUT_DISTANCE (measure distance)
dwTol1 Range of tolerance for D1. Try IF_DS_INPUT_TOL_STD (20).
dwTol2 Range of tolerance for D2. Try IF_DS_INPUT_TOL_STD (20).
dwLevel1 Threshold for D1. Try 100.
dwLevel2 Threshold for D2. Try 100.
dwRepeat1 Repition value for D1. Try IF_DS_INPUT_REP_STD (3).
dwRepeat2 Repition value for D2. Try IF_DS_INPUT_REP_STD (3).
Returns:
FTLIB_ERR_SUCCESS on success
References ft_handle_devices::device, _FT_TRANSFER_AREA::RfModulNr, ft_handle_devices::sdev, ft_handle_devices::transfer_area, and ft_handle_devices::type.
long int SetFtProgramActiv (FT_HANDLE hFt, long int dwMemBlock)
Activate a program.
Will activate a program that has been uploaded to the interface.
Parameters:
hFt Handle of the Interface
dwMemBlock Destination 0 (Flash 1) or 1 (Flash 2)
Returns:
FTLIB_ERR_SUCCESS or FTLIB_ERR_IF_NO_PROGRAM
References ft_handle_devices::device, ft_handle_devices::sdev, and ft_handle_devices::type.
long int SetRealSerial (FT_HANDLE hFt, unsigned char bOn)
Switches between the real serial and 0001 of a device.
Every ft Interface is shipped with 0001 as serial. Nevertheless each has its own serial which can be activated.
Parameters:
hFt Handle of the Interface
bOn 0 to use 0001, else the real serial
Returns:
FTLIB_ERR_SUCCESS on success
References ft_handle_devices::device, ft_handle_devices::sdev, and ft_handle_devices::type.
long int SetRFMode (FT_HANDLE hFt, long int frequency, long int callSign)
Sets the frequency and call sign for a Robo Interface or RF Data Link.
Sets the frequency and call sign which allows to control multiple Interfaces at one RF Data Link. The value won't be lost on power failure.
Parameters:
hFt Handle of the Interface
frequency to use. May be between 2 and 80.
callSign call sign for this Interface. May be between 1 and 8. (ignored for the RF Data Link)
Returns:
FTLIB_ERR_SUCCESS on success
References ft_handle_devices::device, ft_handle_devices::sdev, and ft_handle_devices::type.
long int StartFtProgram (FT_HANDLE hFt, long int dwMemBlock)
Start a program.
Will start a program that has been Successfully uploaded to the interface.
Parameters:
hFt Handle of the Interface
dwMemBlock Destination 0 (Flash 1), 1 (Flash 2) or 2 (Ram)
Returns:
FTLIB_ERR_SUCCESS or FTLIB_ERR_IF_NO_PROGRAM
References ft_handle_devices::device, ft_handle_devices::sdev, and ft_handle_devices::type.
long int StartFtTransferArea (FT_HANDLE hFt, NOTIFICATION_EVENTS * ignored)
Starts the communication thread.
This function is needed to start the communication with the interface in passive mode. Get the handle with GetFtUsbDeviceHandle(), GetFtUsbDeviceHandleSerialNr() or OpenFtCommDevice().
See also:
GetFtUsbDeviceHandle()
GetFtUsbDeviceHandleSerialNr()
OpenFtCommDevice()
Parameters:
hFt Handle of the interface.
ignored The second argument is ignored in this version.
Returns:
Everything except FTLIB_ERR_SUCCESS indicates an error.
Examples:
example.c.
References ft_handle_devices::t.
Referenced by StartFtTransferAreaWithCommunication().
long int StartFtTransferAreaWithCommunication (FT_HANDLE hFt, NOTIFICATION_EVENTS * ignored)
Starts the communication thread.
Since notification are ignored in this version, will just call StartFtTransferArea().
See also:
StartFtTransferArea()
References StartFtTransferArea().
long int StopFtProgram (FT_HANDLE hFt)
Stop a program.
Will stop the current running program that has been uploaded to the interface.
Parameters:
hFt Handle of the Interface
Returns:
FTLIB_ERR_SUCCESS or FTLIB_ERR_IF_NO_PROGRAM
References ft_handle_devices::device, ft_handle_devices::sdev, and ft_handle_devices::type.
long int StopFtTransferArea (FT_HANDLE hFt)
Stops the communication thread.
Warning:
Will block a few microseconds until thread stopped.
This function will stop the communication thread.
See also:
StartFtTransferArea()
Parameters:
hFt Handle of the Interface.
Returns:
Everything except FTLIB_ERR_SUCCESS indicates an error.
Examples:
example.c.
References ft_handle_devices::t, ft_handle_devices::transfer_area, and _FT_TRANSFER_AREA::TransferAktiv.